In [16]:
import numpy as np
import random
a=np.random.randint(1,100,25)
a

array([56, 57, 41, 65, 93, 98, 11, 17, 41,  5, 78,  4, 80, 79, 95, 96, 66,
       33, 68, 25, 40, 66, 26, 53, 72], dtype=int32)

In [17]:
#sort
np.sort(a)

array([ 4,  5, 11, 17, 25, 26, 33, 40, 41, 41, 53, 56, 57, 65, 66, 66, 68,
       72, 78, 79, 80, 93, 95, 96, 98], dtype=int32)

In [3]:
np.sort(a)[::-1]

array([92, 91, 90, 89, 87, 86, 86, 77, 69, 61, 52, 46, 45, 43, 37, 34, 34,
       34, 20, 16, 15, 14, 12,  5,  2], dtype=int32)

In [18]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[25, 80, 61, 83],
       [98, 27, 30, 95],
       [49, 87, 52, 17],
       [ 2, 87, 18, 41],
       [84, 61, 44, 88],
       [20, 80, 21, 20]], dtype=int32)

In [19]:
np.sort(b,axis=0)

array([[ 2, 27, 18, 17],
       [20, 61, 21, 20],
       [25, 80, 30, 41],
       [49, 80, 44, 83],
       [84, 87, 52, 88],
       [98, 87, 61, 95]], dtype=int32)

Append

In [20]:
a

array([56, 57, 41, 65, 93, 98, 11, 17, 41,  5, 78,  4, 80, 79, 95, 96, 66,
       33, 68, 25, 40, 66, 26, 53, 72], dtype=int32)

In [6]:
np.append(a,200)

array([ 43,  15,  61,  92,  45,  91,  86,  34,  90,  77,  37,   5,  14,
        69,  16,  34,  20,  52,   2,  89,  34,  86,  12,  46,  87, 200])

In [11]:
b

array([[ 6, 60, 27, 42],
       [72, 10, 72, 29],
       [24, 73, 11, 69],
       [65, 57, 35, 58],
       [17, 53, 25, 79],
       [24, 10, 39, 66]], dtype=int32)

In [21]:
np.append(b,np.ones((6,1)),axis=1)

array([[25., 80., 61., 83.,  1.],
       [98., 27., 30., 95.,  1.],
       [49., 87., 52., 17.,  1.],
       [ 2., 87., 18., 41.,  1.],
       [84., 61., 44., 88.,  1.],
       [20., 80., 21., 20.,  1.]])

In [22]:
np.ones((3,3),np.int16)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

concatenate

In [23]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

unique

In [24]:
e=np.array([1,1,1,2,2,2,3,1,6,7,8,6])

In [25]:
np.unique(e)

array([1, 2, 3, 6, 7, 8])

Expand_dims

In [26]:
a.shape

(25,)

In [35]:
np.expand_dims(a,axis=1).shape

(25, 1)

Where

In [41]:
np.where(a>20)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 11, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24]),)

In [42]:
#replace all the vale >20 with 0
np.where(a>20,0,a)

array([ 0,  0,  0,  0,  0,  0,  0,  0, 20,  0, 11,  0, 11, 16,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0], dtype=int32)

In [9]:
np.where(a%2==0,0,a)

array([43, 15, 61,  0, 45, 91,  0,  0,  0, 77, 37,  5,  0, 69,  0,  0,  0,
        0,  0, 89,  0,  0,  0,  0, 87], dtype=int32)

argmax

give the maximum element

In [44]:
a

array([84, 32, 63, 30, 71, 25, 41, 47, 20, 34, 11, 70, 11, 16, 75, 72, 71,
       36, 64, 53, 25, 72, 65, 61, 58], dtype=int32)

In [45]:
np.argmax(a)

np.int64(0)

In [47]:
b

array([[ 6, 60, 27, 42],
       [72, 10, 72, 29],
       [24, 73, 11, 69],
       [65, 57, 35, 58],
       [17, 53, 25, 79],
       [24, 10, 39, 66]], dtype=int32)

In [27]:
np.argmax(b,axis=1)

array([3, 0, 1, 1, 3, 1])

Cummulative sum

In [2]:
a

array([99, 81, 61, 21, 95, 89, 80, 31, 15, 15, 35, 80, 69,  4, 89, 35, 64,
       55, 59,  1, 95, 62, 48, 73, 78], dtype=int32)

In [28]:
np.cumsum(a)

array([  56,  113,  154,  219,  312,  410,  421,  438,  479,  484,  562,
        566,  646,  725,  820,  916,  982, 1015, 1083, 1108, 1148, 1214,
       1240, 1293, 1365])

In [5]:
b

array([[69, 81,  4, 25],
       [89, 57, 35, 96],
       [49, 49, 23, 11],
       [46, 30,  9, 99],
       [77, 29, 91,  8],
       [93, 37, 82, 41]], dtype=int32)

In [6]:
np.cumsum(b,axis=0)

array([[ 69,  81,   4,  25],
       [158, 138,  39, 121],
       [207, 187,  62, 132],
       [253, 217,  71, 231],
       [330, 246, 162, 239],
       [423, 283, 244, 280]])

In [7]:
np.cumprod(a)

array([                  99,                 8019,               489159,
                   10272339,            975872205,          86852626245,
              6948210099600,      215394513087600,     3230917696314000,
          48463765444710000,  1696231790564850000,  6571334729221138688,
       -7746505526480220928,  5907466041498219520, -9191100444235459584,
       -8093866295178707968, -1498608827569864704, -8636509221504352256,
        6954789995110662144,  6954789995110662144, -3377737118030954496,
       -6505516507114110976,  1329856911585050624,  4845834177160937472,
        9040184344362090496])

Percentile

In [8]:
a

array([99, 81, 61, 21, 95, 89, 80, 31, 15, 15, 35, 80, 69,  4, 89, 35, 64,
       55, 59,  1, 95, 62, 48, 73, 78], dtype=int32)

In [29]:
np.percentile(a,100) #it give maximum 

np.float64(98.0)

Histogram

In [11]:
a

array([43, 15, 61, 92, 45, 91, 86, 34, 90, 77, 37,  5, 14, 69, 16, 34, 20,
       52,  2, 89, 34, 86, 12, 46, 87], dtype=int32)

In [12]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 4, 1, 4, 3, 1, 2, 1, 4, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

corelation coefficient

In [31]:
salary=np.array([2000,4000,2500,3500,6000])
experience=np.array([1,3,2,4,2])

In [32]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

Flip

In [42]:
np.reshape(a,(5,5))

array([[56, 57, 41, 65, 93],
       [98, 11, 17, 41,  5],
       [78,  4, 80, 79, 95],
       [96, 66, 33, 68, 25],
       [40, 66, 26, 53, 72]], dtype=int32)

In [41]:
np.flip(a)

array([72, 53, 26, 66, 40, 25, 68, 33, 66, 96, 95, 79, 80,  4, 78,  5, 41,
       17, 11, 98, 93, 65, 41, 57, 56], dtype=int32)

Put

In [45]:
a

array([100, 200,  41,  65,  93,  98,  11,  17,  41,   5,  78,   4,  80,
        79,  95,  96,  66,  33,  68,  25,  40,  66,  26,  53,  72],
      dtype=int32)

In [44]:
np.put(a,[0,1],[100,200])