In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
b=np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [7]:
c = np.array([[[1.2, 2.0], [2.0, 3.0]],
              [[2.0, 3.0], [2.0, 3.0]]])
print(c)


[[[1.2 2. ]
  [2.  3. ]]

 [[2.  3. ]
  [2.  3. ]]]


In [2]:
import numpy as np
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
import random
a=np.random.random((3,4))
print(a)

[[0.56537855 0.62728439 0.14113722 0.89501553]
 [0.03762375 0.88702787 0.91687989 0.89311083]
 [0.01121358 0.86127422 0.93699097 0.18428608]]


In [12]:
import random
np.random.randint(3,10,size=(3,4))

array([[9, 7, 7, 9],
       [5, 4, 7, 4],
       [3, 8, 6, 9]], dtype=int32)

In [13]:
#linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [16]:
#identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Numpy Attribute

In [3]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
#ndim
a1.ndim
a2.ndim
a3.ndim

3

In [8]:
#shape
a2.shape
a3.shape

(2, 2, 2)

In [10]:
#size
a3.size
a2.size

12

In [13]:
#itemsize
a2.itemsize

8

In [14]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [16]:
#changing dtype
#astype
a3.astype(np.int32)
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

Array Operation

In [17]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Scaler operation

In [30]:
#arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [21]:
#relational 
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Vector operation

In [23]:
#arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Operation

In [34]:
np.max(a2)
np.sum(a2)
np.min(a2)
np.prod(a2)

np.int64(647647525324800)

In [35]:
np.max(a2,axis=1)

array([15, 19, 23])

In [41]:
#mean/median/std/var
np.mean(a1)
np.median(a2)
np.var(a2)
np.std(a2)

np.float64(3.452052529534663)

Dot product

In [2]:
import numpy as np
a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(4,3)
np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [3]:
#log
np.log(a3)

C:\Users\DELL\AppData\Local\Temp\ipykernel_17180\3879496682.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a3)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [2]:
#round/floor/ceil
import numpy as np
np.floor(np.random.random((2,3))*100)


array([[64., 76.,  5.],
       [59., 60., 58.]])

Index and Slicing

In [3]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [10]:
a1[::-1]
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a2[1,2]
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
a3[1,0,1]

np.int64(5)

In [18]:
#slicing
a1[2:5]
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a2[0,:]
a2[:,2]
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [22]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [38]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [41]:
a2[1,::3]

array([4, 7])

In [44]:
a2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
#3D 
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
a3[0,1,:]

array([3, 4, 5])

In [18]:
a3[1,:,1]

array([10, 13, 16])

In [19]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [21]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [22]:
 #to iterate each element
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshape

In [23]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
#raval
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Stacking

In [25]:
#horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)


In [27]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [28]:
#vstack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Spliting

In [29]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
#horizontal splitging
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [34]:
#vertical spliting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]